# Generated by Django 3.0.11 on 2020-12-04 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='name',
            field=models.TextField(default='Uratex', verbose_name='bed'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='name',
            field=models.TextField(default='Folgers', verbose_name='name'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Bed', verbose_name='bed'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='coffee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Coffee', verbose_name='coffee'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='usana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usana', verbose_name='usana'),
        ),
        migrations.AddField(
            model_name='usana',
            name='name',
            field=models.TextField(default='Cellsentials', verbose_name='usana'),
        ),
    ]
