# Generated by Django 3.0.11 on 2020-12-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201205_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end at'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start at'),
        ),
    ]
