# Generated by Django 3.0.11 on 2020-12-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201205_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleep',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='sleep',
            name='start_at',
        ),
        migrations.AddField(
            model_name='sleep',
            name='slept_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='slept at'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='woke_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='woke at'),
        ),
    ]
