# Generated by Django 3.0.11 on 2020-12-04 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201205_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='bed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Bed', verbose_name='bed'),
        ),
    ]
