# Generated by Django 3.0.11 on 2020-12-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201205_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleep',
            name='coffee_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='coffee at'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='usana_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='usana at'),
        ),
    ]
